[workspace]
members = [
  "contracts/mars-address-provider",
  "contracts/mars-incentives",
  "contracts/mars-ma-token",
  "contracts/mars-oracle/*",
  "contracts/mars-red-bank",
  "contracts/mars-rewards-collector/*",
  "packages/*"
]
default-members = [
  "contracts/mars-address-provider",
  "contracts/mars-incentives",
  "contracts/mars-ma-token",
  "contracts/mars-oracle/*",
  "contracts/mars-red-bank",
  "contracts/mars-rewards-collector/*",
  "packages/mars-outpost",
  "packages/mars-health"
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
