[package]
name = "rover"
version = "0.1.0"
authors = ["larry_0x <larry@delphidigital.io>", "Gabe R. <gabe.r@delphilabs.io>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
mock-red-bank = { version = "1.0", path = "../../contracts/mock-red-bank", features = ["library"] }

cosmwasm-std = "1.0"
cw-storage-plus = "0.14"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = "1.0"
